baseURL = 'https://shiokiriyama.github.io/'
publishDir = 'docs'
languageCode = 'ja'
title = 'Shiokiriyama'
author = "Shiokiriyama"
theme = 'shiokiriyama-theme'
disableKinds = ["taxonomy", "taxonomyTerm"]
